### ISSUE TITLE
generating the data.[Fold].K[K].L[L].[train/test] file

### ISSUE THREAD

**Issue by redna11** [hallogameboy/JEDI#1]
Hi,

Do you provide a script to go from the .neg and .pos files to the file format "data.[Fold].K[K].L[L].[train/test] " used for the training? How do you get from one to the other?
This is an essential step to be able to reproduce your experiment which cannot be easily done at the moment.

Thanks for helping on this and for your work.

**Comment by hallogameboy** [comment]
Hi,

Thanks for being interested in our work. We have updated the script to easily generate the input files for JEDI from given partitioned .pos and .neg files. More details are shown in [this section](https://github.com/hallogameboy/JEDI#generation-script) on the instruction page.

**Comment by redna11** [comment]
works thanks
