### ISSUE TITLE
Reproducing Mouse results and dataset size

### ISSUE THREAD

**Issue by redna11** [hallogameboy/JEDI#2]
Hi,

I am trying to reproduce your results with regards to training on the isoform dataset and testing on the mouse dataset. First thing is in the paper you mention that the mouse dataset is made of 1522 positives and 1522 negatives, whereas in the repo the dataset is 1522 and 1128. 

When training on isoform for 3 periods, the testing on the mouse dataset comes out at 55pc accuracy.

Is that the expected result? (paper says around 88.7pc)

The other way around (training on mouse, testing on isoform) seems to work fine though.

Thanks for your help.

**Comment by hallogameboy** [comment]
Hi,

For the dataset size, we forgot to mention we further use the lincRNAs in those samples as the negative instances. This is why there are only 1,128 cases in our released data.

For the independent study, this case needs a longer junction length. Please try L=128 or so. You should reach our reported numbers after this change.

We will patch the descriptions in our updated version.

**Comment by redna11** [comment]
For future reference, training the Isoform model with L=128, and testing on the mouse data (with L=128), does indeed gives accuracy around 88.7%.
So to have a model which is applicable through different species, one would need to use the larger L model.  Is that expected?

**Comment by hallogameboy** [comment]
It is great to hear you can reproduce our results. For this change, we explain that it would require more general encoded information to make the junction representations able to be generally applied across different species. Hence, it would observe longer flanking regions for higher flexibility of junction modeling.
